// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Dal;
using TaskManager.Entities.Enum;

namespace TaskManager.Dal.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    [Migration("20200613163651_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:Enum:PermissionType", "ProjectModify,ProjectDelete,MilestoneAdd,MilestoneModify,MilestoneDelete,SubTaskAdd,SubTaskModify,SubTaskDelete,TaskAdd,TaskModify,TaskDelete,CommentAdd,CommentModify,CommentDelete,RoleChange,StatusChange,UserInvite,UserKick,TagAdd,TagDelete,TagUpdate,Read,TaskMileStoneChange,TaskAssigneeChange")
                .HasAnnotation("Npgsql:Enum:Status", "None,Open,InProgress,Closed")
                .HasAnnotation("Npgsql:Enum:UnitType", "Comment,Milestone,Project,Task,SubTask")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "role",
                            ClaimValue = "Maintainer_20",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "role",
                            ClaimValue = "Owner_20",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "role",
                            ClaimValue = "Developer_20",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<decimal>("Rank")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78006aefd74b",
                            Name = "Guest",
                            NormalizedName = "GUEST",
                            Rank = 1m
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78006aefd74b",
                            Name = "Developer",
                            NormalizedName = "DEVELOPER",
                            Rank = 2m
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78406aefd74b",
                            Name = "Maintainer",
                            NormalizedName = "MAINTAINER",
                            Rank = 3m
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78406aefd74b",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Rank = 4m
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78006aefd74b",
                            Email = "devidshylyuk85@gmail.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Unspecified).AddTicks(2711), new TimeSpan(0, 3, 0, 0, 0)),
                            LockoutEnabled = false,
                            Name = "David",
                            NormalizedEmail = "DEVIDSHYLYUK85@GMAIL.COM",
                            NormalizedUserName = "DAVID",
                            PasswordHash = "AQAAAAEAACcQAAAAEJMqefM3jQQE7sOvJCM73AKmMaFQqF0t01IbCdmU+x7KcgHlBoETO6+XXtvJ+wB9UA==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Local).AddTicks(3141),
                            SecurityStamp = "9819F4B5-F389-4603-BF0B-1E3C88379627",
                            TwoFactorEnabled = false,
                            UserName = "@devich"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78006aefd74b",
                            Email = "olarevun23@gmail.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Unspecified).AddTicks(5327), new TimeSpan(0, 3, 0, 0, 0)),
                            LockoutEnabled = false,
                            Name = "Ola",
                            NormalizedEmail = "OLAREVUN23@GMAIL.COM",
                            NormalizedUserName = "OLA",
                            PasswordHash = "AQAAAAEAACcQAAAAELhW7WoGTkP1aZcDoN5qwgHILFMMak47gnjEKYQ0YBgcEitvLKiKmpoXYliqdFfMVA==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Local).AddTicks(5363),
                            SecurityStamp = "9819F4B5-F389-4603-BF0B-1E3C88379627",
                            TwoFactorEnabled = false,
                            UserName = "@olga"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cda9194a-63f5-4643-afdd-78006aefd74b",
                            Email = "olegrevun23@gmail.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Unspecified).AddTicks(5389), new TimeSpan(0, 3, 0, 0, 0)),
                            LockoutEnabled = false,
                            Name = "Oleg",
                            NormalizedEmail = "OLEGREVUN23@GMAIL.COM",
                            NormalizedUserName = "OLEG",
                            PasswordHash = "AQAAAAEAACcQAAAAELhW7WoGTkP1aZcDoN5qwgHILFMMak47gnjEKYQ0YBgcEitvLKiKmpoXYliqdFfMVA==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 6, 13, 19, 36, 50, 937, DateTimeKind.Local).AddTicks(5396),
                            SecurityStamp = "9819F4B5-F389-4603-BF0B-1E3C88379627",
                            TwoFactorEnabled = false,
                            UserName = "@olegka"
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.MileStone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("MileStones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UnitId = 50
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<PermissionType>("PermissionType")
                        .HasColumnType("\"PermissionType\"");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionType = PermissionType.Read,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionType = PermissionType.Read,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            PermissionType = PermissionType.CommentAdd,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            PermissionType = PermissionType.CommentDelete,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            PermissionType = PermissionType.CommentModify,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            PermissionType = PermissionType.TagAdd,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            PermissionType = PermissionType.TagDelete,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            PermissionType = PermissionType.TagUpdate,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            PermissionType = PermissionType.Read,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            PermissionType = PermissionType.CommentAdd,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            PermissionType = PermissionType.CommentDelete,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            PermissionType = PermissionType.CommentModify,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            PermissionType = PermissionType.MilestoneAdd,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            PermissionType = PermissionType.MilestoneDelete,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            PermissionType = PermissionType.MilestoneModify,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            PermissionType = PermissionType.TaskAdd,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 17,
                            PermissionType = PermissionType.TaskDelete,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            PermissionType = PermissionType.TaskModify,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            PermissionType = PermissionType.SubTaskAdd,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            PermissionType = PermissionType.SubTaskDelete,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            PermissionType = PermissionType.SubTaskModify,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            PermissionType = PermissionType.TagAdd,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            PermissionType = PermissionType.TagDelete,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            PermissionType = PermissionType.TagUpdate,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            PermissionType = PermissionType.StatusChange,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            PermissionType = PermissionType.TaskMileStoneChange,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            PermissionType = PermissionType.TaskAssigneeChange,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            PermissionType = PermissionType.Read,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            PermissionType = PermissionType.CommentAdd,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            PermissionType = PermissionType.CommentDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 31,
                            PermissionType = PermissionType.CommentModify,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 32,
                            PermissionType = PermissionType.MilestoneAdd,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 33,
                            PermissionType = PermissionType.MilestoneDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 34,
                            PermissionType = PermissionType.MilestoneModify,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 35,
                            PermissionType = PermissionType.TaskAdd,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 36,
                            PermissionType = PermissionType.TaskDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 37,
                            PermissionType = PermissionType.TaskModify,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            PermissionType = PermissionType.SubTaskAdd,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 39,
                            PermissionType = PermissionType.SubTaskDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 40,
                            PermissionType = PermissionType.SubTaskModify,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 41,
                            PermissionType = PermissionType.ProjectDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 42,
                            PermissionType = PermissionType.ProjectModify,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 43,
                            PermissionType = PermissionType.RoleChange,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 44,
                            PermissionType = PermissionType.UserInvite,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 45,
                            PermissionType = PermissionType.UserKick,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 46,
                            PermissionType = PermissionType.TagAdd,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 47,
                            PermissionType = PermissionType.TagDelete,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 48,
                            PermissionType = PermissionType.TagUpdate,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 49,
                            PermissionType = PermissionType.StatusChange,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            PermissionType = PermissionType.TaskMileStoneChange,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            PermissionType = PermissionType.TaskAssigneeChange,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Project", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<int>("Members")
                        .HasColumnType("integer");

                    b.HasKey("UnitId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            UnitId = 20,
                            Members = 1
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.ProjectMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GivenAccess")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TextValue = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            TextValue = "Self-test"
                        },
                        new
                        {
                            Id = 3,
                            TextValue = "Adminka"
                        },
                        new
                        {
                            Id = 4,
                            TextValue = "Done"
                        },
                        new
                        {
                            Id = 5,
                            TextValue = "Blocked"
                        },
                        new
                        {
                            Id = 6,
                            TextValue = "CodeReview"
                        },
                        new
                        {
                            Id = 7,
                            TextValue = "Frontend"
                        },
                        new
                        {
                            Id = 8,
                            TextValue = "Backend"
                        },
                        new
                        {
                            Id = 9,
                            TextValue = "Backlog"
                        },
                        new
                        {
                            Id = 10,
                            TextValue = "Testing"
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.TagOnTask", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("TagId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TagOnTasks");

                    b.HasData(
                        new
                        {
                            TagId = 5,
                            TaskId = 1
                        },
                        new
                        {
                            TagId = 8,
                            TaskId = 1
                        },
                        new
                        {
                            TagId = 9,
                            TaskId = 1
                        },
                        new
                        {
                            TagId = 1,
                            TaskId = 2
                        },
                        new
                        {
                            TagId = 8,
                            TaskId = 2
                        },
                        new
                        {
                            TagId = 6,
                            TaskId = 3
                        },
                        new
                        {
                            TagId = 8,
                            TaskId = 3
                        },
                        new
                        {
                            TagId = 4,
                            TaskId = 4
                        },
                        new
                        {
                            TagId = 8,
                            TaskId = 4
                        },
                        new
                        {
                            TagId = 1,
                            TaskId = 5
                        },
                        new
                        {
                            TagId = 10,
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AssignedId")
                        .HasColumnType("integer");

                    b.Property<int?>("MileStoneId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedId");

                    b.HasIndex("MileStoneId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignedId = 2,
                            MileStoneId = 1,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 5,
                            AssignedId = 2,
                            MileStoneId = 1,
                            UnitId = 5
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.TermInfo", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DueTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Status>("Status")
                        .HasColumnType("\"Status\"");

                    b.HasKey("UnitId");

                    b.ToTable("TermInfos");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            DueTs = new DateTimeOffset(new DateTime(2020, 5, 25, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 930, DateTimeKind.Unspecified).AddTicks(8898), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.Open
                        },
                        new
                        {
                            UnitId = 2,
                            DueTs = new DateTimeOffset(new DateTime(2020, 5, 30, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5777), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        },
                        new
                        {
                            UnitId = 3,
                            DueTs = new DateTimeOffset(new DateTime(2020, 5, 27, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5862), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        },
                        new
                        {
                            UnitId = 4,
                            DueTs = new DateTimeOffset(new DateTime(2020, 5, 26, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5874), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        },
                        new
                        {
                            UnitId = 5,
                            DueTs = new DateTimeOffset(new DateTime(2020, 5, 23, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5881), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.Closed
                        },
                        new
                        {
                            UnitId = 20,
                            DueTs = new DateTimeOffset(new DateTime(2020, 6, 23, 12, 40, 40, 0, DateTimeKind.Unspecified), new TimeSpan(0, -2, 0, 0, 0)),
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5892), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        },
                        new
                        {
                            UnitId = 25,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5900), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        },
                        new
                        {
                            UnitId = 26,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5907), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.Closed
                        },
                        new
                        {
                            UnitId = 40,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5917), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.None
                        },
                        new
                        {
                            UnitId = 41,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5926), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.None
                        },
                        new
                        {
                            UnitId = 42,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5932), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.None
                        },
                        new
                        {
                            UnitId = 50,
                            StartTs = new DateTimeOffset(new DateTime(2020, 6, 13, 19, 36, 50, 933, DateTimeKind.Unspecified).AddTicks(5939), new TimeSpan(0, 3, 0, 0, 0)),
                            Status = Status.InProgress
                        });
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("UnitParentId")
                        .HasColumnType("integer");

                    b.Property<UnitType>("UnitType")
                        .HasColumnType("\"UnitType\"");

                    b.HasKey("UnitId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UnitParentId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            CreatorId = 2,
                            Description = "Create user api, spam list and blocking users",
                            Key = new Guid("dea2c6f6-3064-40fb-9f75-8e695939e839"),
                            Name = "CRUD API creating and deleting users",
                            UnitParentId = 20,
                            UnitType = UnitType.Task
                        },
                        new
                        {
                            UnitId = 2,
                            CreatorId = 2,
                            Description = "Modify database, add email service for client sales",
                            Key = new Guid("814d9772-ef7c-4eb9-a932-18dc89d4a0b4"),
                            Name = "Api for email subscriptions",
                            UnitParentId = 20,
                            UnitType = UnitType.Task
                        },
                        new
                        {
                            UnitId = 3,
                            CreatorId = 2,
                            Description = "Change behaviour from delete cascade to restrict and rework service deleting logic",
                            Key = new Guid("a7d245d0-3280-4ef5-9acb-6787bc194db7"),
                            Name = "Delete cascade",
                            UnitParentId = 20,
                            UnitType = UnitType.Task
                        },
                        new
                        {
                            UnitId = 4,
                            CreatorId = 2,
                            Description = "Plug in PayPal",
                            Key = new Guid("90992949-51c7-4ad1-aa92-086a1c57ba5d"),
                            Name = "Api for donations",
                            UnitParentId = 20,
                            UnitType = UnitType.Task
                        },
                        new
                        {
                            UnitId = 5,
                            CreatorId = 2,
                            Description = "Config docker compose with dotnet and postgres image and write integration tests for content with",
                            Key = new Guid("3310e655-5b08-493c-972c-13f668b5c57e"),
                            Name = "Testing content",
                            UnitParentId = 20,
                            UnitType = UnitType.Task
                        },
                        new
                        {
                            UnitId = 20,
                            CreatorId = 1,
                            Description = "Система отслеживания заданий. Выдача задания менеджером. Статус задания, согласно рабочему процессу. Процент выполнения. Почтовые уведомления клиентам системы. Управление пользователями и их ролями.",
                            Key = new Guid("bff26a36-6cb5-4cef-a7c4-939f6eaf76ca"),
                            Name = "TaskManager",
                            UnitType = UnitType.Project
                        },
                        new
                        {
                            UnitId = 25,
                            CreatorId = 2,
                            Key = new Guid("32ae9833-13f7-4350-a68e-70e0bfeeca30"),
                            Name = "Create postgres image",
                            UnitParentId = 5,
                            UnitType = UnitType.SubTask
                        },
                        new
                        {
                            UnitId = 26,
                            CreatorId = 2,
                            Key = new Guid("02d0d799-c713-4d50-997a-c4b116192153"),
                            Name = "Create dotnet image",
                            UnitParentId = 5,
                            UnitType = UnitType.SubTask
                        },
                        new
                        {
                            UnitId = 40,
                            CreatorId = 2,
                            Key = new Guid("2da24682-8c31-4a23-b1e4-f979e8f80805"),
                            Name = "add doc document with api desc",
                            UnitParentId = 4,
                            UnitType = UnitType.Comment
                        },
                        new
                        {
                            UnitId = 41,
                            CreatorId = 2,
                            Key = new Guid("d719805a-5c72-4473-8e6a-16b23120e185"),
                            Name = "we use postgres 11",
                            UnitParentId = 5,
                            UnitType = UnitType.Comment
                        },
                        new
                        {
                            UnitId = 42,
                            CreatorId = 1,
                            Key = new Guid("2e5bc155-4842-4bf3-94de-36199204d917"),
                            Name = "Ok",
                            UnitParentId = 5,
                            UnitType = UnitType.Comment
                        },
                        new
                        {
                            UnitId = 50,
                            CreatorId = 1,
                            Key = new Guid("2e5bc155-4842-4bf3-94de-36194204d917"),
                            Name = "MileStone1",
                            UnitParentId = 20,
                            UnitType = UnitType.Milestone
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Entities.Tables.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.MileStone", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Unit", "Unit")
                        .WithOne("MileStone")
                        .HasForeignKey("TaskManager.Entities.Tables.MileStone", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Permission", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Project", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Unit", "Unit")
                        .WithOne("Project")
                        .HasForeignKey("TaskManager.Entities.Tables.Project", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.ProjectMember", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Entities.Tables.Identity.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.TagOnTask", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Tag", "Tag")
                        .WithMany("TagOnTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Entities.Tables.Task", "Task")
                        .WithMany("TagOnTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Task", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.User", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedId");

                    b.HasOne("TaskManager.Entities.Tables.MileStone", "MileStone")
                        .WithMany("Tasks")
                        .HasForeignKey("MileStoneId");

                    b.HasOne("TaskManager.Entities.Tables.Unit", "Unit")
                        .WithOne("Task")
                        .HasForeignKey("TaskManager.Entities.Tables.Task", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.TermInfo", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Unit", "Unit")
                        .WithOne("TermInfo")
                        .HasForeignKey("TaskManager.Entities.Tables.TermInfo", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.Entities.Tables.Unit", b =>
                {
                    b.HasOne("TaskManager.Entities.Tables.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManager.Entities.Tables.Unit", "UnitParent")
                        .WithMany("Children")
                        .HasForeignKey("UnitParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
