namespace TaskManager.Entities.Enum
{
    public enum PermissionType
    {
        ProjectModify,
        ProjectDelete,
        MilestoneAdd,
        MilestoneModify,
        MilestoneDelete,
        SubTaskAdd,
        SubTaskModify,
        SubTaskDelete,
        TaskAdd,
        TaskModify,
        TaskDelete,
        CommentAdd,
        CommentModify,
        CommentDelete,
        RoleChange,
        StatusChange,
        UserInvite,
        UserKick,
        TagAdd,
        TagDelete,
        TagUpdate,
        Read,
        TaskMileStoneChange,
        TaskAssigneeChange
    }
}